### ISSUE TITLE
Keylogging Is Not Working On Mac

### ISSUE THREAD

**Issue by Dee2009** [FlexiSPY/flexispy-desktop-beta-testing#10]
Flexispy did not capture any keys since activation. I have tried to disable/enable the feature few times with no success. OS is Yosemite running on 2009 MacBook Pro.

**Comment by Dakota-FlexiSPY** [comment]
@Dee2009 Thank you for bringing this to our attention. We are looking into the cause of this issue, and I'll update you with more information as it comes in.

**Comment by Dakota-FlexiSPY** [comment]
@Dee2009  It appears that the issue originated from our server, and we believe that it's fixed now. Please have a look in your account and let us know whether or not Key Logs are showing up.

**Comment by Dee2009** [comment]
Hi Dakota. Keylogging is still not working on Mac

**Comment by Dakota-FlexiSPY** [comment]
@Dee2009 Thanks for letting us know, our developers are having a look for the problem again.

**Comment by Dee2009** [comment]
Hi Dakota. Any developments on that issue? Still not working on Mac..

**Comment by Dakota-FlexiSPY** [comment]
@Dee2009 We're still trying to get to the bottom of this, but within a couple of days I should have more information to give you.
